export const DEFAULT_SETTINGS = {
  businessName: 'VoltixNepal',
  ownerName: 'Sanjit Mishra',
  tagline: 'Professional Electrical Services in Nepal',
  phone: '+977 9825870047',
  whatsappNumber: '9779825870047',
  email: 'sanjit@voltixnepal.com',
  address: 'Kathmandu, Bagmati Province, Nepal',
  businessHours: 'Sun - Fri: 7:00 AM - 8:00 PM | Sat: Emergency Only',
  emergencyAvailable: true,
  emergencyPhone: '+977 9825870047',
  googleMapsUrl: 'https://maps.google.com/?q=Kathmandu,Nepal',
  footerText: 'Professional electrical installation, emergency repair, and maintenance services across Kathmandu Valley. Safety and punctuality guaranteed by Sanjit Mishra.',
  announcementText: '24/7 Emergency Electrical Breakdown Service Active in Kathmandu Valley.',
  announcementActive: true,
  facebookUrl: 'https://facebook.com/voltixnepal',
  instagramUrl: 'https://instagram.com/voltixnepal',
  tiktokUrl: 'https://tiktok.com/@voltixnepal',
  youtubeUrl: 'https://youtube.com',
  aboutTitle: 'Reliable Electrical Workmanship with Safety at the Core',
  aboutSubtitle: 'Standardized safety, transparent diagnostics, and punctual technician dispatch across Kathmandu Valley.',
  aboutStory: 'VoltixNepal was founded by Sanjit Mishra to address a persistent issue in Kathmandu Valley electrical contracting: the lack of standardized safety, transparent diagnostics, and punctual technician dispatch.',
  aboutMission: 'Protecting lives, eliminating electrical fire hazards, and ensuring electrical installations function safely without voltage fluctuations or insulation failure.',
  aboutVision: "To be Nepal's most trusted and technologically advanced electrical contracting and safety engineering team.",
  aboutOwnerTitle: 'Lead Electrician & Proprietor',
  aboutOwnerBio: 'Certified lead electrician with over 10 years of extensive experience delivering residential wiring, commercial automation, and rapid emergency troubleshooting.',
  aboutOwnerPhoto: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=80',
  aboutCoverPhoto: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
  aboutExperienceYears: 10,
  aboutProjectsDone: 1500,
  aboutHappyClients: 1200,
};

export const STATUS_CONFIG: Record<string, { label: string; bg: string; text: string; border: string }> = {
  NEW: { label: 'New Request', bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200' },
  CONTACTED: { label: 'Contacted', bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  CONFIRMED: { label: 'Confirmed', bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
  IN_PROGRESS: { label: 'In Progress', bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
  COMPLETED: { label: 'Completed', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  CANCELLED: { label: 'Cancelled', bg: 'bg-slate-100', text: 'text-slate-600', border: 'border-slate-300' },
};

export const URGENCY_CONFIG: Record<string, { label: string; badge: string }> = {
  NORMAL: { label: 'Standard (1-2 Days)', badge: 'bg-slate-100 text-slate-800' },
  URGENT: { label: 'Urgent (Today)', badge: 'bg-amber-100 text-amber-900 border border-amber-300' },
  EMERGENCY: { label: 'Emergency (Immediate)', badge: 'bg-red-100 text-red-900 border border-red-300 font-semibold' },
};
