import { DEFAULT_SETTINGS } from './constants';

export const DEFAULT_HERO_SLIDES = [
  {
    id: 'slide-1',
    badge: 'CERTIFIED ELECTRICAL SERVICES',
    title: 'Reliable Electrical Services for Your Home & Business',
    description: 'Professional electrical installation, wiring, troubleshooting, and maintenance services across Kathmandu Valley with guaranteed safety standards.',
    primaryBtnText: 'Request a Service',
    primaryBtnLink: '/request-service',
    secondaryBtnText: 'Call Now',
    secondaryBtnLink: 'tel:+9779825870047',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1600&q=80',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'slide-2',
    badge: '24/7 EMERGENCY ASSISTANCE',
    title: 'Emergency Electrical Breakdown & Short Circuit Repair',
    description: 'Sudden power outages, tripping MCBs, burning smells, or dangerous sparks resolved quickly and safely by experienced technicians.',
    primaryBtnText: 'Emergency Request',
    primaryBtnLink: '/request-service?urgency=EMERGENCY',
    secondaryBtnText: 'WhatsApp Chat',
    secondaryBtnLink: 'https://wa.me/9779825870047?text=Hello%20VoltixNepal,%20I%20have%20an%20urgent%20electrical%20issue.',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1600&q=80',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'slide-3',
    badge: 'RESIDENTIAL & COMMERCIAL',
    title: 'Complete House Wiring & Distribution Board Installation',
    description: 'Conduit piping, load-balanced distribution boards, earthing systems, and premium concealed wiring for new constructions and renovations.',
    primaryBtnText: 'Book Inspection',
    primaryBtnLink: '/request-service',
    secondaryBtnText: 'View Services',
    secondaryBtnLink: '/services',
    imageUrl: 'https://images.unsplash.com/photo-1544725121-be3bf52e2dc8?auto=format&fit=crop&w=1600&q=80',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'slide-4',
    badge: 'POWER BACKUP EXPERTS',
    title: 'Inverter, Solar & Battery Backup Setup & Maintenance',
    description: 'Professional load calculations, pure sine wave inverter installations, and battery maintenance to keep your home powered seamlessly.',
    primaryBtnText: 'Request Inverter Service',
    primaryBtnLink: '/request-service',
    secondaryBtnText: 'Call Now',
    secondaryBtnLink: 'tel:+9779825870047',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1600&q=80',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'slide-5',
    badge: 'MODERN FIXTURES & APPLIANCES',
    title: 'Switchboard Upgrades, Lighting & Appliance Connections',
    description: 'Modular switchboards, energy-efficient LED fixtures, heavy appliance connections (geysers, ACs), and preventive safety inspections.',
    primaryBtnText: 'Schedule Service',
    primaryBtnLink: '/request-service',
    secondaryBtnText: 'Learn More',
    secondaryBtnLink: '/about',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=80',
    isActive: true,
    sortOrder: 5,
  },
];

export const DEFAULT_SERVICES = [
  {
    id: 'srv-1',
    slug: 'house-wiring',
    title: 'Complete House Wiring & Conduit Piping',
    shortDescription: 'Concealed PVC piping, point-wise wire drawing, and master distribution board setup for residential and commercial properties.',
    fullDescription: 'Complete residential and commercial electrical wiring services across Kathmandu Valley. We execute conduit piping, wire sizing, RCCB/ELCB shock prevention, and phase balancing to ensure absolute electrical safety.',
    category: 'Residential',
    priceDisplay: 'Turnkey or Point-wise Quote',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    iconName: 'Wrench',
    benefits: JSON.stringify(['Concealed high-durability conduit piping', 'Flame-retardant copper wiring', 'Load-balanced phase distribution']),
    includedItems: JSON.stringify(['Site inspection and load calculation', 'Conduit pipe grooving and slab layout', 'Switchboard modular boxing']),
    whenNeeded: JSON.stringify(['New house construction in Kathmandu Valley', 'Complete renovation of older apartments', 'Upgrading aluminum to copper wiring']),
    serviceArea: 'Kathmandu, Lalitpur, Bhaktapur & surrounding valley areas',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'srv-2',
    slug: 'fault-finding-repair',
    title: 'Short Circuit & Fault Finding Diagnostics',
    shortDescription: 'Precision multimeter and insulation megger diagnostics to isolate tripped MCBs, burnt cables, and dangerous voltage leaks.',
    fullDescription: 'Recurring circuit trips and sparking switches can lead to devastating electrical fires. Our experienced technician uses advanced diagnostic equipment to trace faults without dismantling your walls.',
    category: 'Emergency',
    priceDisplay: 'Inspection from Rs. 500',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    iconName: 'Zap',
    benefits: JSON.stringify(['Multimeter continuity & insulation testing', 'Fast pin-pointing of hidden wire faults', 'Safe breaker restoration']),
    includedItems: JSON.stringify(['Complete board inspection', 'Short circuit isolation', 'Defective joint replacement']),
    whenNeeded: JSON.stringify(['MCB breaker trips instantly when switched on', 'Burning wire odor or spark inside switchboard', 'Sudden power drop in specific rooms']),
    serviceArea: 'Kathmandu, Lalitpur, Bhaktapur & surrounding valley areas',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'srv-3',
    slug: 'mcb-distribution-board',
    title: 'MCB & Distribution Board (DB) Maintenance',
    shortDescription: 'Upgrading old fuse boxes to modern miniature circuit breakers (MCBs), RCCBs, and phase changeover switches.',
    fullDescription: 'Protect your appliances and family from lethal shocks. We replace obsolete fuse boxes with modern Hager/Schneider/Havells MCB panels equipped with RCCB shock cutoffs.',
    category: 'Installation',
    priceDisplay: 'From Rs. 1,200 + parts',
    imageUrl: 'https://images.unsplash.com/photo-1544725121-be3bf52e2dc8?auto=format&fit=crop&w=800&q=80',
    iconName: 'ShieldCheck',
    benefits: JSON.stringify(['Shock protection via 30mA RCCB', 'Even load distribution across phases', 'Neat labeling for easy identification']),
    includedItems: JSON.stringify(['Old board removal and safety check', 'Busbar balancing and MCB mounting', 'Earth continuity verification']),
    whenNeeded: JSON.stringify(['Old ceramic rewirable fuse boxes still in use', 'Distribution board heating up during peak load', 'Adding dedicated high-load line for geyser/AC']),
    serviceArea: 'Kathmandu, Lalitpur, Bhaktapur & surrounding valley areas',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'srv-4',
    slug: 'inverter-battery-installation',
    title: 'Inverter & Battery Backup Setup',
    shortDescription: 'Accurate wattage sizing, pure sine wave inverter connections, battery water checks, and changeover switchgear.',
    fullDescription: 'Keep your internet, lights, and essential appliances powered seamlessly during load shedding. We configure pure sine wave inverters with tubular batteries for maximum efficiency.',
    category: 'Installation',
    priceDisplay: 'From Rs. 1,000 + cabling',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    iconName: 'BatteryCharging',
    benefits: JSON.stringify(['Optimized battery life and zero overcharging', 'Dedicated inverter sub-circuit separation', 'Safe high-amperage cabling']),
    includedItems: JSON.stringify(['Load calculation and inverter placement', 'Heavy duty DC lug crimping', 'AC input/output phase isolation']),
    whenNeeded: JSON.stringify(['Installing a new inverter for home or clinic', 'Upgrading from small backup to high-capacity battery', 'Inverter humming loudly or not charging']),
    serviceArea: 'Kathmandu, Lalitpur, Bhaktapur & surrounding valley areas',
    isActive: true,
    sortOrder: 4,
  },
];

export const DEFAULT_TESTIMONIALS = [
  {
    id: 't-1',
    customerName: 'Bishal Kumar Sharma',
    location: 'Baneshwor, Kathmandu',
    rating: 5,
    content: 'VoltixNepal did the complete electrical wiring and LED panel fitting for our new 2.5-story house. Every switchboard was neatly aligned and load-balanced. Highly recommended electrician in Kathmandu Valley.',
    date: 'August 2026',
    photoUrl: null,
    isApproved: true,
  },
  {
    id: 't-2',
    customerName: 'Suman Shrestha',
    location: 'Jhamsikhel, Lalitpur',
    rating: 5,
    content: 'Our main MCB kept tripping every time the water heater was switched on. Sanjeet Mishra arrived within 45 minutes of booking, diagnosed a neutral leak with a multimeter, and repaired it safely.',
    date: 'September 2026',
    photoUrl: null,
    isApproved: true,
  },
  {
    id: 't-3',
    customerName: 'Pooja Adhikari',
    location: 'Sallaghari, Bhaktapur',
    rating: 5,
    content: 'Very polite, punctual, and transparent about rates. Installed our 1500VA inverter and backup battery neatly under the staircase. Truly reliable electrical contractor.',
    date: 'July 2026',
    photoUrl: null,
    isApproved: true,
  },
  {
    id: 't-4',
    customerName: 'Rajesh K.C.',
    location: 'Maharajgunj, Kathmandu',
    rating: 5,
    content: 'We remodeled our dental clinic and needed dedicated shock-proof lines for heavy medical autoclaves. Excellent workmanship, clean conduit work, and zero power drop.',
    date: 'September 2026',
    photoUrl: null,
    isApproved: true,
  },
];

export const DEFAULT_FAQS = [
  {
    id: 'faq-1',
    question: 'How quickly can you attend an emergency electrical issue in Kathmandu?',
    answer: 'For emergency calls (such as total blackout, sparking, burning smells, or major circuit breakdown), we prioritize rapid response and typically reach locations across Kathmandu, Lalitpur, and Bhaktapur within 45 to 90 minutes.',
    category: 'Emergency',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'faq-2',
    question: 'How do you charge for electrical repair and installation services?',
    answer: 'For standard repairs and troubleshooting, we charge an inspection fee starting from Rs. 500-600 which covers diagnostic testing. If you proceed with the repair work, the quote is clearly explained before starting. For full house wiring, we provide itemized point-wise quotes.',
    category: 'Pricing',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'faq-3',
    question: 'Do you provide genuine electrical materials and spare parts?',
    answer: 'Yes. We recommend and use certified, high-grade materials (Havells, Finolex, Schneider, Panasonic/Anchor, Pioneer, etc.) with proper safety certifications. If you prefer to supply your own materials, we are completely happy to provide skilled labor only.',
    category: 'Materials',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'faq-4',
    question: 'Why does my MCB breaker trip repeatedly?',
    answer: 'An MCB trips for three main reasons: an electrical overload, a short circuit (phase and neutral touching), or a ground fault. We use multimeters to pinpoint the faulty line safely rather than forcefully keeping the breaker on.',
    category: 'Technical',
    isActive: true,
    sortOrder: 4,
  },
];

export const DEFAULT_BLOG_POSTS = [
  {
    id: 'post-1',
    slug: 'why-mcb-trips-monsoon-nepal',
    title: 'Why Circuit Breakers Trip in Monsoon & How to Fix Them Safely',
    summary: 'High humidity, roof seepage, and moisture inside conduit pipes are the leading causes of tripping MCBs during the rainy season in Kathmandu.',
    content: 'During the monsoon season across Kathmandu Valley, electrical faults surge dramatically due to moisture infiltration. In this guide, electrician Sanjeet Mishra explains how to identify moisture-induced leakage, prevent electrical shocks, and when to call a professional technician.',
    featuredImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    category: 'Troubleshooting',
    tags: 'mcb,tripping,monsoon,safety',
    author: 'Sanjeet Mishra',
    isPublished: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-2',
    slug: 'how-to-calculate-inverter-battery-size',
    title: 'How to Calculate the Right Inverter & Battery Size for Your Home',
    summary: 'Practical guide to calculating total running wattage and selecting the optimal tubular battery capacity (AH) for uninterrupted power in Nepal.',
    content: 'Choosing the right inverter requires calculating peak wattage and total backup hours. Sanjeet Mishra provides a step-by-step formula for sizing 800VA to 2500VA inverter systems for Nepali households.',
    featuredImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    category: 'Power Backup',
    tags: 'inverter,battery,sizing,nepal',
    author: 'Sanjeet Mishra',
    isPublished: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
